language: ruby
before_install: gem install bundler --no-doc
rvm:
  - 2.1
  - 2.2
  - jruby
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y protobuf-compiler
cache: bundler
env:
  global:
    - CODECLIMATE_REPO_TOKEN=ca72e4a3e0b0d78d03adf4e7faa5c3777b27e34b51e54c2ff55ecac1a2293f1f
    - REPORT_COVERAGE=1
